// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "wallet-manager/domain/wallet/entity"

	mock "github.com/stretchr/testify/mock"
)

// IWalletRepository is an autogenerated mock type for the IWalletRepository type
type IWalletRepository struct {
	mock.Mock
}

// AddFund provides a mock function with given fields: ctx, ID, fund
func (_m *IWalletRepository) AddFund(ctx context.Context, ID int64, fund uint64) error {
	ret := _m.Called(ctx, ID, fund)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint64) error); ok {
		r0 = rf(ctx, ID, fund)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, userID
func (_m *IWalletRepository) Create(ctx context.Context, userID int64) (*entity.Wallet, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entity.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, ID
func (_m *IWalletRepository) GetByID(ctx context.Context, ID int64) (*entity.Wallet, error) {
	ret := _m.Called(ctx, ID)

	var r0 *entity.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Wallet); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *IWalletRepository) GetByUserID(ctx context.Context, userID int64) (*entity.Wallet, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entity.Wallet
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wallet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubtractFund provides a mock function with given fields: ctx, ID, fund
func (_m *IWalletRepository) SubtractFund(ctx context.Context, ID int64, fund uint64) error {
	ret := _m.Called(ctx, ID, fund)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint64) error); ok {
		r0 = rf(ctx, ID, fund)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIWalletRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIWalletRepository creates a new instance of IWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIWalletRepository(t mockConstructorTestingTNewIWalletRepository) *IWalletRepository {
	mock := &IWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
